# Generated by Django 3.2.12 on 2022-03-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.IntegerField(verbose_name=50),
        ),
    ]
