# Generated by Django 3.2.12 on 2022-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingredient', '0002_alter_ingredient_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.IntegerField(),
        ),
    ]
