# Generated by Django 3.2.12 on 2022-03-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingredient', '0003_alter_ingredient_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_alcoholic',
            field=models.BooleanField(default=True),
        ),
    ]
